name: test React-app
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - 'hotfix-*'
      # ex: hotfix-wording
      - 'feature/**'
      # ex : feature/user/update
    path-ignore:
      - .github/workflows/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # récupérer le code en fonction de la branche courante
      - name: code
        uses: actions/checkout@v3
      # installation d'une certaine version de Node
      - name: install Node V18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # installation du "node_modules"
      - name: install app
        run: npm install
      # exécution des tests
      # attention : ajouter dans la package.json
      #             "test": "react-scripts test --watchAll=false"
      - name: test
        run: npm run test